apiVersion: v1
appVersion: 0.15.1
description: Alertmanager instance created by the CoreOS Prometheus Operator
engine: gotpl
home: https://github.com/prometheus/alertmanager
keywords:
- alertmanager
- monitoring
- prometheus
maintainers:
- email: gianrubio@gmail.com
  name: Giancarlo Rubio
name: alertmanager
sources:
- https://github.com/coreos/prometheus-operator
- https://github.com/prometheus/alertmanager
version: 0.1.7
