{{- if and .Values.prometheus.enabled .Values.prometheus.alerts.enabled }}

{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- $project := .Values.project -}}

{{- with merge $noValues $overrides $common -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.fullname" $root }}-rules
  namespace: {{ .Values.prometheus.namespace | default "monitoring" | quote }}
  labels:
    role: alert-rules
    prometheus: {{ .Values.prometheus.instance | default "kube-prometheus" | quote }}
    {{- include "common.labels" $root | nindent 4 }}
spec:
  groups:
  - name: {{ .Values.project.app }}.rules
    rules:
    - alert: {{ .Values.prometheus.prefix }}PodFailure
      expr: 'kube_pod_status_phase{phase=~"Failed|Error",namespace="{{ .Release.Namespace }}"} > 0'
      for: 2m
      labels:
        severity: critical
        {{- include "common.labels" $root | nindent 8 }}
      annotations:
        summary: 'Pod: {{`{{ $labels.pod }}`}} is down with and error or failure'
        description: 'Pod: {{ `{{ $labels.namespace }}` }}/{{ `{{ $labels.pod }}` }} is down with and error or failure!'

    - alert: {{ .Values.prometheus.prefix }}ServiceDown
      expr: 'up{namespace="{{ .Release.Namespace }}"} == 0'
      for: 5m
      labels:
        severity: warning
        {{- include "common.labels" $root | nindent 8 }}
      annotations:
        description: 'Services down in {{ `{{ $labels.namespace }}` }}'
        summary: Service Failure

    - alert: {{ .Values.prometheus.prefix }}PodPendingUnknown
      expr: 'kube_pod_status_phase{phase=~"Pending|Unknown",namespace="{{ .Release.Namespace }}"} > 0'
      for: 5m
      labels:
        severity: warning
        {{- include "common.labels" $root | nindent 8 }}
      annotations:
        summary: 'Pod: {{ `{{ $labels.pod }}` }} is in pending state for 15 minutes'
        description: 'Pod: {{ `{{ $labels.namespace }}` }}/{{ `{{ $labels.pod }}` }} is in pending state for 15 minutes!'

    - alert: {{ .Values.prometheus.prefix }}KubePodCrashLooping
      expr: 'rate(kube_pod_container_status_restarts_total{namespace="{{ .Release.Namespace }}"}[15m]) * 60 * 5 > 0'
      for: 10m
      labels:
        severity: critical
        {{- include "common.labels" $root | nindent 8 }}
      annotations:
        summary: 'Pod {{ .Release.Namespace }}/{{ `{{ $labels.pod }}` }} ({{ `{{ $labels.container }}` }}) is restarting {{ `{{ printf "%.2f" $value }}` }} times / 5 minutes.'
        description: 'Pod {{ .Release.Namespace }}/{{ `{{ $labels.pod }}` }} ({{ `{{ $labels.container }}` }}) is restarting {{ `{{ printf "%.2f" $value }}` }} times / 5 minutes.'

    - alert: {{ .Values.prometheus.prefix }}JvmMemoryFillingUp
      expr: jvm_memory_bytes_used / jvm_memory_bytes_max{area="heap"} > 0.8
      for: 5m
      labels:
        severity: warning
        {{- include "common.labels" $root | nindent 8 }}
      annotations:
        summary: "JVM memory filling up (instance {{ `{{ $labels.instance }}` }})"
        description: "JVM memory is filling up (> 80%)\n  VALUE = {{ `{{ $value }}` }}\n  LABELS: {{ `{{ $labels }}` }}"
{{- end }}
{{- end -}}