{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}

{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}

{{- with merge $noValues $overrides $common -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" $root }}-metrics
  labels:
    {{- include "common.labels" $root | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.prometheus.serviceMonitor.targetPort | default .Values.ports.default.prometheus }}
    targetPort: metrics
  selector:
    {{- include "common.service.selectors" $root | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.fullname" $root }}
{{- if .Values.prometheus.namespace }}
  namespace: {{ .Values.prometheus.namespace }}
{{- else }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
  labels:
    app: {{ include "common.fullname" $root }}
    app.kubernetes.io/name: {{ template "common.fullname" $root }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "common.chart" $root }}
    prometheus: {{ .Values.prometheus.instance }}
{{- if .Values.prometheus.serviceMonitor.labels }}
{{ toYaml .Values.prometheus.serviceMonitor.labels | indent 4}}
{{- end }}
spec:
  jobLabel: {{ template "common.fullname" $root }}
  selector:
    matchLabels:
      {{- include "common.service.selectors" $root | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    path: {{ .Values.prometheus.serviceMonitor.path }}
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
{{- end }}
{{- end -}}
